language: node_js
node_js:
  - "8"

env:
  - SNYK_TOKEN="698bcdaf-92de-4a07-bdb7-df4a3fc358b3"

install:
  - npm i -g elm
  - npm install
  - cd test/fixtures
  - elm-make --yes
  - cd ../..

script:
  - npm run-script snyk
  - npm test
