language: node_js
node_js:
  - '8'
env:
  global:
    - SNYK_TOKEN="698bcdaf-92de-4a07-bdb7-df4a3fc358b3"
install:
  - npm install
  - cd test/fixtures
  - travis_retry travis_wait ../../node_modules/elm/binwrappers/elm-make --yes
  - cd ../..
script:
  - npm run-script snyk
  - npm run build
  - travis_wait npm test
after_success:
  - npm run coverage
