language: node_js
node_js:
  - '8'

cache:
  - tests/fixtures/elm-stuff/build-artifacts
  - sysconfcpus

before_install:
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - npm i -g elm@0.18
  - npm install
  - npm run snyk:t
  - cd test/fixtures
  - travis_retry elm-package install -y
  - |
    mv $(npm config get prefix)/bin/elm-make $(npm config get prefix)/bin/elm-make-old
    printf '%s\n\n' '#!/bin/bash' 'echo "Running elm-make with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make-old "$@"' > $(npm config get prefix)/bin/elm-make
    chmod +x $(npm config get prefix)/bin/elm-make
  - elm-make --yes
  - cd ../..

script:
  - npm run build
  - npm test

after_success:
  - npm run snyk:m
  - npm run coverage
